# Generated by Django 3.1.7 on 2021-03-28 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('enrollment', models.CharField(max_length=10, unique=True, verbose_name='num empleado')),
                ('anti', models.IntegerField(blank=True, default=0, null=True)),
                ('CURP', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('NSS', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('area', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
