# Generated by Django 3.1.7 on 2021-03-28 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210328_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
