# Generated by Django 3.1.7 on 2021-04-23 02:06

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='private'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Object Upload'),
        ),
    ]
